In [95]:
# Representing the in 10x2 Dimension
import numpy as np
Day_number=np.arange(1,11)
steps_walked=[6011,3025,9590,8092,2100,300,7000,9080,10100,11089]
arr=np.array([Day_number,steps_walked])
arr=arr.T
print(arr)
new=arr[:,1]+2000
arr[:,1]=new
print()
print(arr)
la=arr[:,1]>9000
la
new_=arr[la]
new_

[[    1  6011]
 [    2  3025]
 [    3  9590]
 [    4  8092]
 [    5  2100]
 [    6   300]
 [    7  7000]
 [    8  9080]
 [    9 10100]
 [   10 11089]]

[[    1  8011]
 [    2  5025]
 [    3 11590]
 [    4 10092]
 [    5  4100]
 [    6  2300]
 [    7  9000]
 [    8 11080]
 [    9 12100]
 [   10 13089]]


array([[    3, 11590],
       [    4, 10092],
       [    8, 11080],
       [    9, 12100],
       [   10, 13089]])

In [109]:
import pandas as pd
lee={'Days':[1,2,3,4,5,6,7,8,9,10],
    'Steps_walked':[6011,3025,9590,8092,2100,300,7000,9080,10100,11089]}
lee_=pd.DataFrame(lee)
print(lee_,'\n')
print("...The data after adding 2000...")
ste=lee_.Steps_walked.add(2000)
print(ste,'\n')
gre=lee_.Steps_walked>9000
print('...The steps greater than 9000...')
print(ste[gre])

   Days  Steps_walked
0     1          6011
1     2          3025
2     3          9590
3     4          8092
4     5          2100
5     6           300
6     7          7000
7     8          9080
8     9         10100
9    10         11089 

...The data after adding 2000...
0     8011
1     5025
2    11590
3    10092
4     4100
5     2300
6     9000
7    11080
8    12100
9    13089
Name: Steps_walked, dtype: int64 

...The steps greater than 9000...
2    11590
7    11080
8    12100
9    13089
Name: Steps_walked, dtype: int64


In [110]:
import pandas as pd
import random
for i in range(10):
    print(random.randint(100,10000))

1992
7794
2743
1065
4595
1656
2549
9685
3810
9065


In [151]:
import random
import pandas as pd
lee={'Days':[1,2,3,4,5,6,7,8,9,10],
    'Steps_walked':[6011,3025,9590,8092,2100,300,7000,9080,10100,11089]}
lee_=pd.DataFrame(lee)
print(lee_,'\n')
print("...The data after adding 2000...")
ste=lee_.Steps_walked.add(2000)
print(ste,'\n')
gre=lee_.Steps_walked>9000
print('...The steps greater than 9000...')
print(ste[gre])

   Days  Steps_walked
0     1          6011
1     2          3025
2     3          9590
3     4          8092
4     5          2100
5     6           300
6     7          7000
7     8          9080
8     9         10100
9    10         11089 

...The data after adding 2000...
0     8011
1     5025
2    11590
3    10092
4     4100
5     2300
6     9000
7    11080
8    12100
9    13089
Name: Steps_walked, dtype: int64 

...The steps greater than 9000...
2    11590
7    11080
8    12100
9    13089
Name: Steps_walked, dtype: int64


## calculating aggregate function

In [169]:
import pandas as pd
marks={'Chemistry':[67,90,66,32,72,45,60,98],
      'Physics':[45,92,72,92,72,34,72,45]}
marks_=pd.DataFrame(marks,index=['subodh','Ram','Abdul','JOhn','Nandini','Zoya','Shivam','James'])
print(marks_,'\n')
print(marks_.sum(),'\n')
print('Chemistry Average:',marks_.Chemistry.mean(),'\n')
print(marks_.mean())

         Chemistry  Physics
subodh          67       45
Ram             90       92
Abdul           66       72
JOhn            32       92
Nandini         72       72
Zoya            45       34
Shivam          60       72
James           98       45 

Chemistry    530
Physics      524
dtype: int64 

Chemistry Average: 66.25 

Chemistry    66.25
Physics      65.50
dtype: float64


### Melt Function

In [181]:
import pandas as pd
df=pd.DataFrame(data={
  'Day':['MON','TUE','WED','THU'],
'Google':[1129,1132,1186,1299],
    'Apple':[191,196,182,190],
    'Samsung':[192,195,180,169]   
})
print(df,'\n')
# By using melt function it can be reshaped 
reshape_df=df.melt(id_vars=['Day'])# id_vars is the column where we donot want to change anything..
print("..After reshaping..")
reshape_df

   Day  Google  Apple  Samsung
0  MON    1129    191      192
1  TUE    1132    196      195
2  WED    1186    182      180
3  THU    1299    190      169 

..After reshaping..


Day variable  value
0   MON   Google   1129
1   TUE   Google   1132
2   WED   Google   1186
3   THU   Google   1299
4   MON    Apple    191
5   TUE    Apple    196
6   WED    Apple    182
7   THU    Apple    190
8   MON  Samsung    192
9   TUE  Samsung    195
10  WED  Samsung    180
11  THU  Samsung    169

### Filter function

In [194]:
ls=[i for i in range(50)]
evenlist=list(filter(lambda x:True if x%2==0 else False,ls))
oddlist=list(filter(lambda x:True if x%2!=0 else False,ls))
print('Evenlist')
print(evenlist,'\n')
print('odd list')
print(oddlist)

Evenlist
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48] 

odd list
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49]


In [200]:
def oddeven(x):
    if x%2==0:
        return True
    else:
        return False
ls_=[j for j in range(50)]
evels=list(filter(oddeven,ls_))
print("Even Numbers..")
print(evels)

Even Numbers..
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]


### Auto-MPG

In [20]:

import pandas as pd
df=pd.read_csv('auto-mpg.csv')
df.head()
# Engineer want to know MPG>29,Horsepower<93.5,weight<2500

en=df.loc[(df['mpg']>29)& (df['weight']<2500)]
print(en)
# Engineer want to know displacement>262,Horsepower>126,weight in range[2800,3600]
en_=df.loc[(df['displacement']>262)& (df['weight']>=2800)& (df['weight']<=3600)]
print(en_)

      mpg  cylinders  displacement horsepower  weight  acceleration  \
51   30.0          4          79.0         70    2074          19.5   
52   30.0          4          88.0         76    2065          14.5   
53   31.0          4          71.0         65    1773          19.0   
54   35.0          4          72.0         69    1613          18.0   
129  31.0          4          79.0         67    1950          19.0   
..    ...        ...           ...        ...     ...           ...   
384  32.0          4          91.0         67    1965          15.7   
385  38.0          4          91.0         67    1995          16.2   
391  36.0          4         135.0         84    2370          13.0   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   

     model year  origin             car name  
51           71       2          peugeot 304  
52           71       2            fiat 124b  
53    

### Rainfall dataset

In [34]:
df=pd.read_csv('rainfall.csv')
print(df)
# The disrict that gets highest annual rainfall
sortdf=df.sort_values(by='ANNUAL',ascending=False)
highest=sortdf.iloc[0,1]
print("District with highest rainfall:",highest)
# top 5 district with highest annual rainfall
print(sortdf.head(5),'\n')
# dropping the months
drdf=df.drop(['Jan-Feb','Mar-May','Jun-Sep','Oct-Dec'],axis=1)
print('..Dropped data..')
print(drdf)

                   STATE_UT_NAME        DISTRICT    JAN   FEB    MAR    APR  \
0    ANDAMAN And NICOBAR ISLANDS         NICOBAR  107.3  57.9   65.2  117.0   
1    ANDAMAN And NICOBAR ISLANDS   SOUTH ANDAMAN   43.7  26.0   18.6   90.5   
2    ANDAMAN And NICOBAR ISLANDS   N & M ANDAMAN   32.7  15.9    8.6   53.4   
3              ARUNACHAL PRADESH           LOHIT   42.2  80.8  176.4  358.5   
4              ARUNACHAL PRADESH      EAST SIANG   33.3  79.5  105.9  216.5   
..                           ...             ...    ...   ...    ...    ...   
636                       KERALA          IDUKKI   13.4  22.1   43.6  150.4   
637                       KERALA        KASARGOD    2.3   1.0    8.4   46.9   
638                       KERALA  PATHANAMTHITTA   19.8  45.2   73.9  184.9   
639                       KERALA         WAYANAD    4.8   8.3   17.5   83.3   
640                  LAKSHADWEEP     LAKSHADWEEP   20.8  14.7   11.8   48.9   

       MAY    JUN     JUL    AUG    SEP    OCT    N

### houseprice prediction

In [6]:
import pandas as pd
df=pd.read_csv('homeprices.csv')
print(df)
inp=df.drop('price','columns')
out=df.drop('area','columns')
print()
print('Input data')
print(inp,'\n')
print('Output data')
print(out)
import sklearn
from sklearn import linear_model
model=linear_model.LinearRegression()
model.fit(inp,out)
res=model.predict([[5000]])
print('..Predicted value..')
print(res)
acc=model.score(inp,out)*100
print("Accuracy:",acc)


   area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000


<ipython-input-6-273eb9c7c304>:4: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  inp=df.drop('price','columns')
<ipython-input-6-273eb9c7c304>:5: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  out=df.drop('area','columns')



Input data
   area
0  2600
1  3000
2  3200
3  3600
4  4000 

Output data
    price
0  550000
1  565000
2  610000
3  680000
4  725000


/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


..Predicted value..
[[859554.79452055]]
Accuracy: 95.84301138199486


### Multilinear regression

In [19]:
df=pd.read_csv('homeprices_Mul.csv')
print(df,'\n')
medval=df.bedrooms.median()
print('Median:',medval)
df.bedrooms=df.bedrooms.fillna(medval)
print(df)
# separating input and output
inp=df.drop('price','columns')
out=df.drop(['area','bedrooms','age'],'columns')
print()
print('Input data')
print(inp,'\n')
print('Output data')
print(out)
from sklearn import linear_model
model=linear_model.LinearRegression()
model.fit(inp,out)
res=model.predict([[3000,2,18]])
print("Predicted result:",res)
acc=model.score(inp,out)*100
print("Predicted accuray:",acc)

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000 

Median: 4.0
   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000


<ipython-input-19-5505ca1dc2de>:8: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  inp=df.drop('price','columns')
<ipython-input-19-5505ca1dc2de>:9: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  out=df.drop(['area','bedrooms','age'],'columns')



Input data
   area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8
5  4100       6.0    8 

Output data
    price
0  550000
1  565000
2  610000
3  595000
4  760000
5  810000


/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


Predicted result: [[546117.16549229]]
Predicted accuray: 95.50196399325819
